# This is a basic workflow to help you get started with Actions

name: CI-backend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ prod ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Step 1 - Checkout of prod branch
        uses: actions/checkout@v2


      - name: Step 2 - Setup JDK
      - uses: action/setup-java@v1
        with:
          java-version: 11

      - name: Step 3 - Build backend
        run: mvn -B package --file backend/pom.xml
      
      - name: Step 4 - Build docker image
        run: docker buid -t backend backend/Dockerimage
      
      - name: Step 5 - Run docker container
        run: docker run -p 8080:8080 backend
