# This is a basic workflow to help you get started with Actions

name: CI-backend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ prod ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Step 1 - Checkout of prod branch
        uses: actions/checkout@v2

      - name: Step 2 - Build backend
        run: mvn -B package --file backend/pom.xml
        
      - name: Step 3 - Remove depricated container 
        run: docker stop backend-container || true && docker rm backend-container || true
      
      - name: Step 3 - Build docker image
        run: docker build -t backend-image backend/.
      
      - name: Step 4 - Run docker container
        run: docker run -d --name backend-container -p 8080:8080 backend-image
        
